import { Router } from "express";

import userRoutes from "../modules/user/user.routes";
import authRoutes from "../modules/auth/auth.routes";
import serviceRoutes from "../modules/service/service.routes";
import jobRoutes from "../modules/job/job.routes";
import bookingRoutes from "../modules/booking/booking.routes";
import customOrderRoutes from "../modules/customOrder/customOrder.routes";
import paymentRoutes from "../modules/payment/payment.routes";
import epsRoutes from "../modules/eps/eps.routes";
import payoutRoutes from "../modules/payout/payout.routes";
import reviewRoutes from "../modules/review/review.routes";
import chatRoutes from "../modules/chat/chat.routes";
import messageRoutes from "../modules/message/message.routes";
import callRoutes from "../modules/call/call.routes";
import appointmentRoutes from "../modules/appointment/appointment.routes";
import recordingRoutes from "../modules/recording/recording.routes";
import enrollmentRoutes from "../modules/enrollment/enrollment.routes";
import dawraRoutes from "../modules/dawra/dawra.routes";
import courseRoutes from "../modules/course/course.routes";
import freeClassBookingRoutes from "../modules/freeClassBooking/freeClassBooking.routes";
import uploadRoutes from "../modules/upload/upload.routes";
import adminRoutes from "../modules/admin/admin.routes";
import moderatorRoutes from "../modules/moderator/moderator.routes";
import notificationRoutes from "../modules/notification/notification.routes";
import teacherApplicationRoutes from "../modules/teacherApplication/teacherApplication.routes";
import savedTeacherRoutes from "../modules/savedTeacher/savedTeacher.routes";
import paymentMethodRoutes from "../modules/paymentMethod/paymentMethod.routes";

const router = Router();

router.use(userRoutes);
router.use("/auth", authRoutes);
router.use("/saved-teachers", savedTeacherRoutes);
router.use(paymentMethodRoutes);
router.use(serviceRoutes);
router.use(jobRoutes);
router.use(bookingRoutes);
router.use(customOrderRoutes);
router.use(paymentRoutes);
router.use(epsRoutes);
router.use(payoutRoutes);
router.use(reviewRoutes);
router.use(chatRoutes);
router.use(messageRoutes);
router.use(callRoutes);
router.use(appointmentRoutes);
router.use(recordingRoutes);
router.use(enrollmentRoutes);
router.use(dawraRoutes);
router.use(courseRoutes);
router.use(freeClassBookingRoutes);
router.use(uploadRoutes);
router.use(adminRoutes);
router.use(moderatorRoutes);
router.use(notificationRoutes);
router.use(teacherApplicationRoutes);

export default router;
